server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: apalon13
    url: jdbc:postgresql://localhost:5432/ifar_uz
  servlet:
    multipart:
      max-file-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show_sql: true
